[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[toolchain]
package_manager = "yarn"
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[workspace]
members = [
    "programs/vault-stake",
    "programs/vault-mint"
]

[provider]
cluster = "localnet"
wallet = "~/.config/solana/hastra-localnet-id.json"

[test]
startup_wait = 5000
shutdown_wait = 5000
upgradeable = false

[[test.validator.clone]]
address = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"

[[test.validator.clone]]
address = "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL"


